---
images_folder: "data/words/"
labels_file: "data/labels.json"
image:
    image_size:
        y_size: 128
        x_size: 384
        num_channels: 1
    convert_to_grayscale: false
train:
    train_on_subset:
        enabled: false
        random_seed: 33
        dataset_fraction: 0.8
    optimizer: "adam"      #adam, adagrad, adadelta, rmsprop, sgd
    learning_rate: 0.001
    batch_size: 256
    num_epochs: 50
    use_multiprocessing: false
    num_workers: 1
    output:
        output_graph: "models/graph.json"
        output_weights: "models/weights.h5"
predict:
    graph_file: "models/graph.json"
    weights_file: "models/weights.h5"
    batch_size: 256
network:
    num_filters: [16, 32, 64, 128, 256, 512]
    conv_kernels: [[7, 7], [5, 5], [5, 5], [3, 3], [3, 3], [3, 3]]
    use_batch_norm: true
    latent_dim: 512
    max_seq_lenght: 55
    loss: "categorical_crossentropy"
# data_aug:
#     use_data_aug: false
#     rotation_range: 5
#     width_shift_range: 0.05
#     height_shift_range: 0.05
#     zoom_range: [0.95, 1.05]
#     horizontal_flip: false
#     vertical_flip: false
#     shear_range: 2.
callbacks:
    early_stopping:
        enabled: true
        monitor: "val_loss"
        patience: 10
    model_best_checkpoint:
        enabled: true
        out_file: "checkpoints/snapshot_best.h5"
        monitor: "val_loss"
    model_last_checkpoint:
        enabled: true
        out_file: "checkpoints/snapshot_last.h5"
    tensorboard:
        enabled: true
        log_dir: "checkpoints/"
